### ISSUE TITLE
Bridging between DDS and RMW Zenoh using `zenoh-plugin-ros2dds` does not work

### ISSUE THREAD

**Issue by lukaszanger** [osrf/rmw_zenoh#552]
We are trying to bridge traffic from DDS to RMW Zenoh which does not work.

We have the following setup (find the minimal setup as Docker Compose setup below):
- Publisher runs in a container with DDS based on ROS Jazzy. We use the [`zenoh-plugin-ros2dds`](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds) to bridge between DDS and Zenoh.
- Subscriber runs in a container with RMW Zenoh based on ROS Jazzy.

Result: The topic published by the publisher (DDS), respectively by the `zenoh-plugin-ros2dds`, does not reach the subscriber (RMW Zenoh). It cannot be subscribed there.

**Our question**: Is it somehow possible to bridge between DDS and RMW Zenoh using the  [`zenoh-plugin-ros2dds`](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds)?

### Minimal setup
Above mentioned issue can be reproduced using the following minimal example by running `docker compose up`.  We observe that the container `subscriber-rmw-zenoh-ping1` crashes since the topic `/ping1`, which is, on sender side, sent via`zenoh-plugin-ros2dds`, is not available. 

We have the following two topics:
- `/ping1`: DDS -> `zenoh-plugin-ros2dds` -> RMW Zenoh (does not work)
- `/ping2`: RMW Zenoh -> RMW Zenoh (works as expected)

Is there any configuration how `/ping1` can be bridged successfully to RMW Zenoh?

Thank you in advance for any advice!

docker-compose.yml:
```yaml
# docker-compose.yml
services:

  publisher-dds-ping1:
    image: ros:jazzy
    command: "ros2 topic pub /ping1 std_msgs/msg/Float32 '{data: 3.0}'"
    networks: [net1]

  zenoh-bridge-pub-dds:
    image: eclipse/zenoh-bridge-ros2dds:1.2.1
    command: -c /config.json5
    environment:
      ROS_DISTRO: jazzy
    volumes:
      - ./SESSION_CONFIG.json5:/config.json5
    networks: [net1]

  publisher-rmw-zenoh-ping2:
    image: ros:jazzy
    command: |
      bash -c "apt update && 
      apt install -y ros-jazzy-rmw-zenoh-cpp && 
      source /opt/ros/jazzy/setup.bash &&
      ros2 topic pub /ping2 std_msgs/msg/Float32 '{data: 3.0}'"
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_SESSION_CONFIG_URI=/config.json5
    volumes:
      - ./SESSION_CONFIG.json5:/config.json5
    networks: [net1]

  zenoh-router:
    image: eclipse/zenoh:1.2.1
    networks: [net1,net2]

  subscriber-rmw-zenoh-ping1:
    image: ros:jazzy
    command: |
      bash -c "apt update && 
      apt install -y ros-jazzy-rmw-zenoh-cpp && 
      source /opt/ros/jazzy/setup.bash &&
      ros2 topic echo --spin-time 5 /ping1"
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_SESSION_CONFIG_URI=/config.json5
    volumes:
      - ./SESSION_CONFIG.json5:/config.json5
    networks: [net2]

  subscriber-rmw-zenoh-ping2:
    image: ros:jazzy
    command: |
      bash -c "apt update && 
      apt install -y ros-jazzy-rmw-zenoh-cpp && 
      source /opt/ros/jazzy/setup.bash &&
      ros2 topic echo --spin-time 5 /ping2"
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - ZENOH_SESSION_CONFIG_URI=/config.json5
    volumes:
      - ./SESSION_CONFIG.json5:/config.json5
    networks: [net2]

networks:
  net1:
  net2:
```

SESSION_CONFIG.json5:
```json
//SESSION_CONFIG.json5
{
    mode: "router",
    connect: {
        endpoints: [
            "tcp/zenoh-router:7447"
        ]
    },
}
```
